name: Autoupdate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

    - name: Set up git user
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: '1.24'
        cache-dependency-path: tools/go.sum

    - name: Build tooling
      run: scripts/build-tools.sh

    - name: Run autoupdate
      run: bin/image-mirror-tools autoupdate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
