name: Mirror Images

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug logging"
        required: false
        type: boolean

jobs:
  mirror-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Read secrets into environment
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/application-collection/credentials username | APPCO_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/application-collection/credentials password | APPCO_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials username | PRIME_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials password | PRIME_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials username | PRIME_STAGING_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials password | PRIME_STAGING_PASSWORD

      - name: Install regsync
        run: |
          curl --silent --fail --location --output regsync https://github.com/regclient/regclient/releases/download/v0.8.3/regsync-linux-amd64
          chmod +x regsync

      - name: Mirror images
        run: |
          export PATH=$PATH:$(pwd)
          if [ "${{ inputs.debug }}" = "true" ]; then
            time regsync once --logopt json --missing --config regsync.yaml --verbosity debug
          else
            time regsync once --logopt json --missing --config regsync.yaml
          fi
