name: Mirror Daily Images

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug logging"
        required: false
        type: boolean

jobs:
  mirror-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Read secrets into environment
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

      - name: Install regsync
        run: |
          curl --silent --fail --location --output regsync https://github.com/regclient/regclient/releases/download/v0.8.3/regsync-linux-amd64
          chmod +x regsync

      - name: Mirror daily images
        run: |
          export PATH=$PATH:$(pwd)
          if [ "${{ inputs.debug }}" = "true" ]; then
            time regsync once --logopt json --config regsync-daily.yaml --verbosity debug
          else
            time regsync once --logopt json --config regsync-daily.yaml
          fi
